"""
XGBoost Model for Product Demand Forecasting

This script creates and trains an XGBoost model using the features generated
from the feature_engineering pipeline. It uses only the features defined in
the feature_generators folder.
"""

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime


def load_and_prepare_data():
    """
    Load the data with features and prepare it for XGBoost training.
    
    Returns:
        tuple: (X_train, X_test, y_train, y_test, feature_names)
    """
    print("Loading data with features...")
    
    # Load the data
    data_path = "../feature_engineering/data_with_features_uncompressed.csv"
    df = pd.read_csv(data_path)
    
    print(f"Loaded {len(df)} rows and {len(df.columns)} columns")
    
    # Define feature columns (only those generated by feature generators)
    feature_columns = [
        # Categorical features
        'department', 'category', 'location', 'isholiday',
        
        # Day-based lag features
        'onedaylag', 'twodaylag', 'fourdaylag', 'eightdaylag',
        
        # Week-based lag features
        'oneweeklag', 'twoweeklag', 'fourweeklag', 'eightweeklag',
        
        # Month-based lag features
        'onemonthlag', 'twomonthlag', 'fourmonthlag',
        
        # Year-based features
        'prevyearweek', 'prev2yearweek', 'prevyearmonth', 'prev2yearmonth'
    ]
    
    # Check which features actually exist in the data
    available_features = [col for col in feature_columns if col in df.columns]
    missing_features = [col for col in feature_columns if col not in df.columns]
    
    print(f"Available features: {len(available_features)}")
    print(f"Missing features: {len(missing_features)}")
    if missing_features:
        print(f"Missing: {missing_features}")
    
    # Prepare features and target
    X = df[available_features].copy()
    y = df['sales'].copy()
    
    # Handle missing values
    print("Handling missing values...")
    X = X.fillna(0)  # Fill missing values with 0 for lag features
    
    # Convert categorical features to numeric if needed
    categorical_features = ['department', 'category', 'location', 'isholiday']
    for feature in categorical_features:
        if feature in X.columns:
            if X[feature].dtype == 'object':
                X[feature] = pd.Categorical(X[feature]).codes
    
    print(f"Feature matrix shape: {X.shape}")
    print(f"Target shape: {y.shape}")
    
    return X, y, available_features


def train_xgboost_model(X, y, feature_names):
    """
    Train an XGBoost model for demand forecasting.
    
    Args:
        X (pd.DataFrame): Feature matrix
        y (pd.Series): Target variable (sales)
        feature_names (list): List of feature names
        
    Returns:
        tuple: (model, X_test, y_test, predictions)
    """
    print("Splitting data into train and test sets...")
    
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, shuffle=False
    )
    
    print(f"Training set: {X_train.shape}")
    print(f"Test set: {X_test.shape}")
    
    # Define XGBoost parameters
    params = {
        'objective': 'reg:squarederror',
        'eval_metric': 'rmse',
        'max_depth': 6,
        'learning_rate': 0.1,
        'n_estimators': 100,
        'subsample': 0.8,
        'colsample_bytree': 0.8,
        'random_state': 42,
        'n_jobs': -1
    }
    
    print("Training XGBoost model...")
    print(f"Parameters: {params}")
    
    # Create and train the model
    model = xgb.XGBRegressor(**params)
    model.fit(
        X_train, y_train,
        eval_set=[(X_train, y_train), (X_test, y_test)],
        verbose=False
    )
    
    # Make predictions
    print("Making predictions...")
    y_pred = model.predict(X_test)
    
    return model, X_test, y_test, y_pred


def evaluate_model(y_test, y_pred):
    """
    Evaluate the model performance.
    
    Args:
        y_test (pd.Series): True values
        y_pred (np.array): Predicted values
        
    Returns:
        dict: Evaluation metrics
    """
    print("Evaluating model performance...")
    
    # Calculate metrics
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    
    metrics = {
        'MSE': mse,
        'RMSE': rmse,
        'MAE': mae,
        'R2': r2
    }
    
    print("Model Performance:")
    print(f"  Mean Squared Error (MSE): {mse:.4f}")
    print(f"  Root Mean Squared Error (RMSE): {rmse:.4f}")
    print(f"  Mean Absolute Error (MAE): {mae:.4f}")
    print(f"  R-squared (R2): {r2:.4f}")
    
    return metrics


def plot_feature_importance(model, feature_names, top_n=15):
    """
    Plot feature importance from the trained model.
    
    Args:
        model: Trained XGBoost model
        feature_names (list): List of feature names
        top_n (int): Number of top features to show
    """
    print(f"Plotting top {top_n} feature importances...")
    
    # Get feature importance
    importance = model.feature_importances_
    
    # Create DataFrame
    feature_importance_df = pd.DataFrame({
        'feature': feature_names,
        'importance': importance
    }).sort_values('importance', ascending=False)
    
    # Plot
    plt.figure(figsize=(10, 8))
    sns.barplot(data=feature_importance_df.head(top_n), 
                x='importance', y='feature')
    plt.title(f'Top {top_n} Feature Importances')
    plt.xlabel('Importance')
    plt.tight_layout()
    plt.savefig('feature_importance.png', dpi=300, bbox_inches='tight')
    plt.show()
    
    print("Top 10 Most Important Features:")
    for i, row in feature_importance_df.head(10).iterrows():
        print(f"  {row['feature']}: {row['importance']:.4f}")


def plot_predictions(y_test, y_pred, sample_size=1000):
    """
    Plot actual vs predicted values and save predictions to CSV files.
    
    Args:
        y_test (pd.Series): True values
        y_pred (np.array): Predicted values
        sample_size (int): Number of samples to plot
    """
    print("Plotting predictions and saving to CSV...")
    
    # Create predictions DataFrame with all data
    predictions_df = pd.DataFrame({
        'actual_sales': y_test.values,
        'predicted_sales': y_pred
    })
    
    # Save daily predictions to CSV
    predictions_df.to_csv('predictions_daily.csv', index=False)
    print("Daily predictions saved to 'predictions_daily.csv'")
    
    # Create weekly aggregated predictions by consecutive 7-day periods
    n_records = len(predictions_df)
    predictions_df['week_group'] = predictions_df.index // 7
    
    weekly_predictions = predictions_df.groupby('week_group').agg({
        'actual_sales': 'sum',
        'predicted_sales': 'sum'
    }).reset_index()
    
    # Rename week_group to week for clarity
    weekly_predictions = weekly_predictions.rename(columns={'week_group': 'week'})
    
    # Save weekly predictions to CSV
    weekly_predictions.to_csv('predictions_weekly.csv', index=False)
    print("Weekly predictions saved to 'predictions_weekly.csv'")
    
    print(f"Daily predictions: {len(predictions_df)} records")
    print(f"Weekly predictions: {len(weekly_predictions)} records")
    
    # Sample data for plotting
    if len(y_test) > sample_size:
        indices = np.random.choice(len(y_test), sample_size, replace=False)
        y_test_sample = y_test.iloc[indices]
        y_pred_sample = y_pred[indices]
    else:
        y_test_sample = y_test
        y_pred_sample = y_pred
    
    # Create plots
    fig, axes = plt.subplots(1, 2, figsize=(15, 6))
    
    # Scatter plot
    axes[0].scatter(y_test_sample, y_pred_sample, alpha=0.5)
    axes[0].plot([y_test_sample.min(), y_test_sample.max()], 
                 [y_test_sample.min(), y_test_sample.max()], 'r--', lw=2)
    axes[0].set_xlabel('Actual Sales')
    axes[0].set_ylabel('Predicted Sales')
    axes[0].set_title('Actual vs Predicted Sales')
    
    # Residuals plot
    residuals = y_test_sample - y_pred_sample
    axes[1].scatter(y_pred_sample, residuals, alpha=0.5)
    axes[1].axhline(y=0, color='r', linestyle='--')
    axes[1].set_xlabel('Predicted Sales')
    axes[1].set_ylabel('Residuals')
    axes[1].set_title('Residuals Plot')
    
    plt.tight_layout()
    plt.savefig('predictions_analysis.png', dpi=300, bbox_inches='tight')
    plt.show()


def save_model_and_results(model, metrics, feature_names):
    """
    Save the trained model and results.
    
    Args:
        model: Trained XGBoost model
        metrics (dict): Evaluation metrics
        feature_names (list): List of feature names
    """
    print("Saving model and results...")
    
    # Save model
    model.save_model('xgboost_demand_forecast.json')
    
    # Save feature names
    with open('feature_names.txt', 'w') as f:
        for feature in feature_names:
            f.write(f"{feature}\n")
    
    # Save metrics
    with open('model_metrics.txt', 'w') as f:
        f.write("XGBoost Demand Forecasting Model Results\n")
        f.write("=" * 50 + "\n")
        f.write(f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("Performance Metrics:\n")
        for metric, value in metrics.items():
            f.write(f"  {metric}: {value:.4f}\n")
        f.write(f"\nNumber of features used: {len(feature_names)}\n")
        f.write(f"Features: {', '.join(feature_names)}\n")
    
    print("Model saved as 'xgboost_demand_forecast.json'")
    print("Results saved as 'model_metrics.txt'")
    print("Feature names saved as 'feature_names.txt'")


def main():
    """
    Main function to run the XGBoost demand forecasting pipeline.
    """
    print("=" * 60)
    print("XGBOOST DEMAND FORECASTING MODEL")
    print("=" * 60)
    
    try:
        # Step 1: Load and prepare data
        X, y, feature_names = load_and_prepare_data()
        
        # Step 2: Train model
        model, X_test, y_test, y_pred = train_xgboost_model(X, y, feature_names)
        
        # Step 3: Evaluate model
        metrics = evaluate_model(y_test, y_pred)
        
        # Step 4: Plot results
        plot_feature_importance(model, feature_names)
        plot_predictions(y_test, y_pred)
        
        # Step 5: Save model and results
        save_model_and_results(model, metrics, feature_names)
        
        print("=" * 60)
        print("XGBOOST MODEL TRAINING COMPLETED SUCCESSFULLY!")
        print("=" * 60)
        print(f"Final R2 Score: {metrics['R2']:.4f}")
        print(f"Final RMSE: {metrics['RMSE']:.4f}")
        
    except Exception as e:
        print(f"Error during model training: {str(e)}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
